"""add agent and observability tables

Revision ID: 1a6121910829
Revises: 10f74a2d5c85
Create Date: 2026-06-08 11:10:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a6121910829"
down_revision: Union[str, Sequence[str], None] = "10f74a2d5c85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column(
            "agent_name",
            sa.Enum(
                "sales",
                "recommendation",
                "inventory",
                "payment",
                "fulfillment",
                "loyalty_offers",
                "supplier",
                "customer_generator",
                "post_purchase",
                name="agentname",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "started",
                "completed",
                "failed",
                name="agentrunstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("input_state", sa.JSON(), nullable=True),
        sa.Column("output_state", sa.JSON(), nullable=True),
        sa.Column("langsmith_trace_id", sa.String(length=255), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_runs_session_id_status",
        "agent_runs",
        ["session_id", "status"],
        unique=False,
    )
    op.create_table(
        "agent_conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("customer_id", sa.String(length=36), nullable=False),
        sa.Column(
            "agent_name",
            sa.Enum(
                "sales",
                "recommendation",
                "inventory",
                "payment",
                "fulfillment",
                "loyalty_offers",
                "supplier",
                "customer_generator",
                "post_purchase",
                name="agentname",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", name="conversationrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_conversations_customer_id",
        "agent_conversations",
        ["customer_id"],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("customer_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("is_accepted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendations_product_id_is_accepted",
        "recommendations",
        ["product_id", "is_accepted"],
        unique=False,
    )
    op.create_table(
        "supply_recommendations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("recommended_quantity", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="supplyrecommendationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supply_orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("supply_recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("quantity_ordered", sa.Integer(), nullable=False),
        sa.Column("cost", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "delivered",
                name="supplyorderstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("expected_delivery_day", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supply_recommendation_id"],
            ["supply_recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_event_log_session_id",
        "event_log",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_log_session_id", table_name="event_log")
    op.drop_table("event_log")
    op.drop_table("supply_orders")
    op.drop_table("supply_recommendations")
    op.drop_index(
        "ix_recommendations_product_id_is_accepted", table_name="recommendations"
    )
    op.drop_table("recommendations")
    op.drop_index(
        "ix_agent_conversations_customer_id", table_name="agent_conversations"
    )
    op.drop_table("agent_conversations")
    op.drop_index("ix_agent_runs_session_id_status", table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
